Edit command
AY2223S2-CS2103T-F12-1/tp pull request #56
Opened 2023-03-10 16:47 UTC by owen-yap

- Added edit command
- Made changes to AddressBook, ReadOnlyAddressBook and Model so that they can process Doctors

2023-03-11 06:44 UTC, vigonometry commented on src/main/java/seedu/address/model/person/Doctor.java
> +                .append("; Specialty: ")
```suggestion
.append("; Speciality: ")
```
Standardise spelling across Docedex

2023-03-11 06:47 UTC, vigonometry commented on src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
> +            + PREFIX_SPECIALITY + "SPECIALITY "
```suggestion
+ PREFIX_SPECIALTY + "SPECIALTY"
```

Standardise spelling across Docedex and use US English standard.

2023-03-11 06:49 UTC, vigonometry requested changes
Request updates on PREFIX + help string to match class names and US English standard.

2023-03-12 17:37 UTC, owen-yap commented
Made a few changes to Add Command, changed the way doctors are added so that it is added under a separate list then persons. This will allow the edit command to work properly. 

@vigonometry

2023-03-13 01:01 UTC, vigonometry approved these changes

2023-03-13 01:02 UTC, vigonometry approved these changes
LGTM

2023-03-13 01:02 UTC, merged